### ISSUE TITLE
merge_PEP725: untar fails on Windows for files containing reserved character '|'

### ISSUE THREAD

**Issue by dabasler** [khufkens/phenor#8]
https://github.com/khufkens/phenor/blob/afe44ff7a5929c95e0010cfe4e3166d174853a07/R/merge_pep725.r#L52

Untar fails on Windows systems (using the  internal implementation of tar written in R) for filenames containing the reserved characters '|' as for example in 'PEP725_AT_Betula(Betula_pendula_(B._verrucosa|_B._alba)).csv'

**Comment by khufkens** [comment]
Temporary fix implemented only raises a warning and skips those files. This is a PEP725 issue basically. The solution is to install GNU tar on a Windows system I think, and not use the internal untar routine of R. The current warning reads:

Internal untar failed: special characters are not allowed.
               Install GNU tar to avoid this issue.
              (https://www.gnu.org/software/tar/)

**Comment by khufkens** [comment]
going to close this for now, might reopen later for a more comprehensive solution.
